### ISSUE TITLE
Twitter/Facebook cards don't show track previews

### ISSUE THREAD

**Issue by oisinq** [oisinq/amhran#11]
When you post a link to a track on Facebook/Twitter, it doesn't show a preview of the track itself. I tried using React Helmet to solve this, but it didn't work for me. Maybe because the site is hosted statically on Netlify. If anyone could figure this out, that would be great!

<img width="352" alt="screen shot 2018-09-13 at 17 23 12" src="https://user-images.githubusercontent.com/5693967/45501681-c5aa5380-b779-11e8-96df-7d4bd0213aa2.png">

**Comment by allanleonardjr** [comment]
Hey @oisinq mind if I help you out with this?

**Comment by oisinq** [comment]
@allanleonardjr Feel free, I'd really appreciate any help!

**Comment by allanleonardjr** [comment]
Just quickly glancing at the running site, I see that both the homepage "/" and a specific archive page like "/033" but have the same Open Graph tags. This is why when you share to facebook, for instance, you are shown the information for your website and not for the artist/track.

1. What social information should be shown when the user navigates to:
    - Home ("/")
    - Specific Archive ("/33")
1. Is there ever an instance where you actually want your website/company/application's social information shown when the user navigates Home ("/")?

**Comment by oisinq** [comment]
1. For both pages, I think it should show a personalised site description based on the current showcased artist. I don't think there should be any difference between the two types of page.
2. I don't think so. I think keeping it personalised makes the most sense to me.

**Comment by allanleonardjr** [comment]
Sounds good, I'll get something whipped up now.

**Comment by allanleonardjr** [comment]
@oisinq do you have any questions about my pull request?

**Comment by allanleonardjr** [comment]
....you there?

**Comment by oisinq** [comment]
@allanleonardjr Sorry for blanking you, I haven't worked on this repo properly since mid-2018. I'm going through your PR now and it's looking really great!
